name: Test & build 

on:
  pull_request: 
    branches: 
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "18.x"

      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.0'
      
      - name: Get Flutter packages
        run: flutter pub get

      - name: Check for lints
        run: flutter analyze

      - name: Build APK
        run: flutter build apk
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
